name: copied files

on: [push]

# on:
#   schedule:
#     - cron: '*/15 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
    - name: Run a multi-line script
      run: |
        echo Running script...,
        python clone-openiti-repos.py
        python generate-OpenITI-metadata.py
        
    - name: Commit files
      run: |
        git config --local user.email "sohailsmerchant@github.com"
        git config --local user.name "sohailmerchant"
        git add OpenITI_metadata_light.json OpenITI_metadata_light.csv OpenITI_metadata_complete.yml
        git commit -m "Add changes" || echo "No changes to commit"
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_ACTION_TOKEN }}
